In [319]:
import sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=sys.maxsize)

In [320]:
df= pd.read_csv(r'C:\Users\Isshaan Singh\Downloads\ColorDetect.csv')

In [321]:
df.head()

             Color_name                  Color Hex value    R    G    B
0    air_force_blue_raf   Air Force Blue (Raf)   #5d8aa8   93  138  168
1   air_force_blue_usaf  Air Force Blue (Usaf)   #00308f    0   48  143
2  air_superiority_blue   Air Superiority Blue   #72a0c1  114  160  193
3       alabama_crimson        Alabama Crimson   #a32638  163   38   56
4            alice_blue             Alice Blue   #f0f8ff  240  248  255

In [322]:

df= df.drop('Color', axis=1)

In [323]:
df.shape

(865, 5)

In [324]:
df.info

<bound method DataFrame.info of                Color_name Hex value    R    G    B
0      air_force_blue_raf   #5d8aa8   93  138  168
1     air_force_blue_usaf   #00308f    0   48  143
2    air_superiority_blue   #72a0c1  114  160  193
3         alabama_crimson   #a32638  163   38   56
4              alice_blue   #f0f8ff  240  248  255
..                    ...       ...  ...  ...  ...
860         yellow_orange   #ffae42  255  174   66
861        yellow_process   #ffef00  255  239    0
862            yellow_ryb   #fefe33  254  254   51
863                zaffre   #0014a8    0   20  168
864     zinnwaldite_brown   #2c1608   44   22    8

[865 rows x 5 columns]>

In [325]:
df.isnull().sum()

Color_name    0
Hex value     0
R             0
G             0
B             0
dtype: int64

In [326]:
df.describe()

                R           G           B
count  865.000000  865.000000  865.000000
mean   158.598844  124.683237  119.087861
std     85.338432   76.270225   78.343862
min      0.000000    0.000000    0.000000
25%    101.000000   64.000000   53.000000
50%    178.000000  123.000000  119.000000
75%    236.000000  190.000000  186.000000
max    255.000000  255.000000  255.000000

In [327]:
df.dtypes

Color_name    object
Hex value     object
R              int64
G              int64
B              int64
dtype: object

In [328]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


df['Color_name'] = le.fit_transform(df['Color_name'])

In [329]:
df[[c for c in df if c not in ['Hex value']] 
       + ['Hex value']]

     Color_name    R    G    B Hex value
0             0   93  138  168   #5d8aa8
1             1    0   48  143   #00308f
2             2  114  160  193   #72a0c1
3             3  163   38   56   #a32638
4             4  240  248  255   #f0f8ff
..          ...  ...  ...  ...       ...
860         860  255  174   66   #ffae42
861         861  255  239    0   #ffef00
862         862  254  254   51   #fefe33
863         863    0   20  168   #0014a8
864         864   44   22    8   #2c1608

[865 rows x 5 columns]

In [330]:
df[[c for c in df if c not in ['Color_name']] 
       + ['Color_name']]

    Hex value    R    G    B  Color_name
0     #5d8aa8   93  138  168           0
1     #00308f    0   48  143           1
2     #72a0c1  114  160  193           2
3     #a32638  163   38   56           3
4     #f0f8ff  240  248  255           4
..        ...  ...  ...  ...         ...
860   #ffae42  255  174   66         860
861   #ffef00  255  239    0         861
862   #fefe33  254  254   51         862
863   #0014a8    0   20  168         863
864   #2c1608   44   22    8         864

[865 rows x 5 columns]

In [331]:
df['R'] = df['R'].apply(lambda x: hex(x))
df['G'] = df['G'].apply(lambda x: hex(x))
df['B'] = df['B'].apply(lambda x: hex(x))

In [332]:
df.dtypes

Color_name     int32
Hex value     object
R             object
G             object
B             object
dtype: object

In [333]:
df['R'] = df['R'].apply(lambda x: x[2:])
df['G'] = df['G'].apply(lambda x: x[2:])
df['B'] = df['B'].apply(lambda x: x[2:])

In [334]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['R'] = le.fit_transform(df['R'])

In [335]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['G'] = le.fit_transform(df['G'])

In [336]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['B'] = le.fit_transform(df['B'])

In [337]:
df= df.drop('Hex value', axis=1)

In [338]:
# concatenate values in each row
df['hex_value'] = df['R'].astype(str) + df['G'].astype(str) + df['B'].astype(str)

In [339]:
df[[c for c in df if c not in ['Color_name']] 
       + ['Color_name']]

       R    G    B  hex_value  Color_name
0     62  120  149   62120149           0
1      0   33  125     033125           1
2     82  142  173   82142173           2
3    127   22   40    1272240           3
4    205  226  229  205226229           4
..   ...  ...  ...        ...         ...
860  220  156   49   22015649         860
861  220  218    0    2202180         861
862  219  232   35   21923235         862
863    0    5  149      05149         863
864   24    7  110     247110         864

[865 rows x 5 columns]

In [340]:
df.head()

   Color_name    R    G    B  hex_value
0           0   62  120  149   62120149
1           1    0   33  125     033125
2           2   82  142  173   82142173
3           3  127   22   40    1272240
4           4  205  226  229  205226229

In [341]:
df[[c for c in df if c not in ['Color_name']] 
       + ['Color_name']]

       R    G    B  hex_value  Color_name
0     62  120  149   62120149           0
1      0   33  125     033125           1
2     82  142  173   82142173           2
3    127   22   40    1272240           3
4    205  226  229  205226229           4
..   ...  ...  ...        ...         ...
860  220  156   49   22015649         860
861  220  218    0    2202180         861
862  219  232   35   21923235         862
863    0    5  149      05149         863
864   24    7  110     247110         864

[865 rows x 5 columns]

In [342]:
df

     Color_name    R    G    B  hex_value
0             0   62  120  149   62120149
1             1    0   33  125     033125
2             2   82  142  173   82142173
3             3  127   22   40    1272240
4             4  205  226  229  205226229
..          ...  ...  ...  ...        ...
860         860  220  156   49   22015649
861         861  220  218    0    2202180
862         862  219  232   35   21923235
863         863    0    5  149      05149
864         864   24    7  110     247110

[865 rows x 5 columns]

In [343]:
X = df.iloc[:, 0:-1].values

y = df.iloc[:, -1].values

In [344]:
X

array([[  0,  62, 120, 149],
       [  1,   0,  33, 125],
       [  2,  82, 142, 173],
       [  3, 127,  22,  40],
       [  4, 205, 226, 229],
       [  5, 191,  22,  38],
       [  6, 161,  81,   1],
       [  7, 203, 202, 184],
       [  8, 193,  27,  64],
       [  9, 220, 172,   0],
       [ 10, 220, 107,   0],
       [ 11, 220,  32,  45],
       [ 12, 117,  84, 183],
       [ 13, 128, 180,  41],
       [ 14, 207, 221, 222],
       [ 15, 169, 131, 100],
       [ 16, 110,  74, 114],
       [ 17,  97,  10,  29],
       [ 18, 215, 215, 195],
       [ 19,   0, 110,   0],
       [ 20, 106, 164,   0],
       [ 21, 216, 187, 159],
       [ 22,   0, 233, 229],
       [ 23,  92, 233, 192],
       [ 24,  48,  65,  17],
       [ 25,  36,  50,  58],
       [ 26, 197, 194,  89],
       [ 27, 143, 171, 163],
       [ 28, 100, 151,  89],
       [ 29, 220, 135,  84],
       [ 30, 129,  26,  26],
       [ 31, 218, 217,   0],
       [ 32,  78, 108, 111],
       [ 33,  58, 112,  31],
       [ 34,   0, 108, 229],
       [ 35, 205, 233, 229],
       [ 36, 102, 188, 220],
       [ 37, 125, 183, 221],
       [ 38, 209, 176, 174],
       [ 39,  16, 153, 184],
       [ 40, 215, 211, 163],
       [ 41, 220, 206,  37],
       [ 42,  90, 141,  16],
       [ 43,  97, 114, 113],
       [ 44, 116, 101, 106],
       [ 45, 153, 192, 210],
       [ 46, 122, 111,  95],
       [ 47, 210, 223, 200],
       [ 48, 120,  21,  49],
       [ 49, 220, 208, 176],
       [ 50,  38,  27,  15],
       [ 51, 219,  93,  77],
       [ 52, 156,  61,  65],
       [ 53,   0,   0,   0],
       [ 54,  38, 173,  16],
       [ 55,  19,  38,  25],
       [ 56,  36,  43,  38],
       [ 57, 220, 215, 184],
       [ 58, 129,  95,  82],
       [ 59,  29, 122, 211],
       [ 60, 136, 209, 217],
       [ 61, 215, 220, 169],
       [ 62,   0,   0, 229],
       [ 63, 126, 144, 188],
       [ 64,  13,  99, 228],
       [ 65,  70, 135, 183],
       [ 66, 172, 134, 166],
       [ 67,   0, 129, 156],
       [ 68,   0, 117, 168],
       [ 69,  31,  36, 135],
       [ 70,  14,  53, 228],
       [ 71,   3,  80, 111],
       [ 72, 103,  27, 206],
       [ 73, 186,  75, 114],
       [ 74,  88,  50,  43],
       [ 75,   0, 131, 164],
       [ 76, 191, 198, 180],
       [ 77, 168,   0,   0],
       [ 78,   0,  88,  61],
       [ 79, 100,  35,  79],
       [ 80,   0,  94, 229],
       [ 81, 146, 148,  49],
       [ 82, 167,  47,  68],
       [ 83,  11, 154, 194],
       [ 84,  70, 233,   0],
       [ 85, 156, 130, 208],
       [ 86, 160,  17,  55],
       [ 87, 220,   0, 109],
       [ 88,  93, 212, 202],
       [ 89, 174, 140, 212],
       [ 90, 209, 169, 229],
       [ 91, 220,  67, 144],
       [ 92, 216,  79, 109],
       [ 93,   0,  48,  22],
       [ 94, 169, 108,  34],
       [ 95, 114,  57,   0],
       [ 96, 129,  26,  26],
       [ 97, 220, 175, 183],
       [ 98, 195, 232, 229],
       [ 99, 205, 200, 113],
       [100,  46,  78,  94],
       [101,  94,   0,  17],
       [102, 186, 166, 117],
       [103, 168,  67,   0],
       [104, 197,  98,  65],
       [105, 103,  36,  21],
       [106, 154,  36, 145],
       [107,  80,  25,  81],
       [108,  56,  86,  97],
       [109,  63, 139, 141],
       [110, 110, 145, 158],
       [111,   0,  89,  44],
       [112, 201, 117,  29],
       [113, 191,   0,  19],
       [114, 220, 224,   0],
       [115, 130, 105,  74],
       [116,  48,  39,  18],
       [117,  12,  59,  27],
       [118, 127, 175, 154],
       [119, 158, 136,  89],
       [120, 203, 169, 183],
       [121,  87, 116,  89],
       [122, 220, 218,   0],
       [123, 220, 109,   0],
       [124, 192,  95, 105],
       [125,   0, 172, 229],
       [126,  59,  23,  17],
       [127, 161,  13,  42],
       [128,   0, 185, 135],
       [129, 114,   0,   9],
       [130, 179,   0,  47],
       [131, 199,  58,  49],
       [132, 220,   0,  40],
       [133, 220, 148, 180],
       [134, 144,  10,  11],
       [135, 117, 168, 201],
       [136, 201, 127,  18],
       [137,  64,  26, 103],
       [138, 111, 143, 186],
       [139, 136, 206, 156],
       [140,   0, 105, 148],
       [141,  26, 114, 107],
       [142, 143, 233, 229],
       [143,  47, 133, 188],
       [144, 186,  34,  81],
       [145, 200,  42, 114],
       [146,   0, 105, 148],
       [147,  23,  64, 169],
       [148,  77, 137, 175],
       [149,   0, 104, 146],
       [150, 188,  43,  33],
       [151, 124, 102,  73],
       [152, 215, 194, 146],
       [153,  34,  51,  62],
       [154, 194, 125, 153],
       [155, 187, 233,   0],
       [156,  92, 233,   0],
       [157, 186,  34,  81],
       [158, 220, 165, 177],
       [159, 169,  74,  75],
       [160, 186,  93, 142],
       [161, 132,  63,  92],
       [162, 134,  40,  14],
       [163,  89,  45,   0],
       [164, 175,  87,  14],
       [165, 220, 149,   0],
       [166, 116, 111, 106],
       [167, 191,  48,  36],
       [168, 175,  87,  14],
       [169, 192, 189, 140],
       [170, 216, 185, 211],
       [171,   0,  53, 152],
       [172, 175,  87,  14],
       [173,  79,  60,  39],
       [174, 119, 201, 229],
       [175, 213, 113, 104],
       [176,   0,  30,  81],
       [177, 105, 128, 153],
       [178, 149,  97,  35],
       [179, 182, 120,  85],
       [180, 137,  93,  87],
       [181, 167,  91,  65],
       [182, 117,  84,  84],
       [183, 220,  40,   0],
       [184, 220, 108,  64],
       [185, 213, 113, 104],
       [186, 220,  46,  47],
       [187, 102,  45,  52],
       [188, 216, 216,  76],
       [189, 144,  10,  11],
       [190,  68, 131, 216],
       [191, 220, 226, 200],
       [192, 220, 226, 211],
       [193, 220, 170, 197],
       [194, 220, 231, 188],
       [195, 184,   5,  44],
       [196, 155,   0,  34],
       [197,   0, 233, 229],
       [198,   0, 165, 214],
       [199, 220, 233,  33],
       [200, 205, 206,  32],
       [201,   0,   0, 121],
       [202,  69,  49,  18],
       [203,  62,  41,  68],
       [204, 128,   0,   0],
       [205,  93,  51, 108],
       [206, 116,  87,  79],
       [207, 169,  73,  52],
       [208,   0, 121, 121],
       [209,  56,  86, 103],
       [210, 149, 116, 157],
       [211, 133, 151, 150],
       [212,   1,  35,  17],
       [213,   0,  47,  88],
       [214,   9,  20,  18],
       [215, 154, 165,  89],
       [216,  46,  43,  34],
       [217,  83,  61, 133],
       [218, 104,   0, 121],
       [219,   0,  36,  84],
       [220,  57,  89,  30],
       [221, 220, 122,   0],
       [222, 117,  35, 183],
       [223,  86, 139, 182],
       [224,  27, 174,  44],
       [225, 114,  93, 194],
       [226, 159,  42,  19],
       [227, 195,  66, 111],
       [228,   0,  36, 135],
       [229, 100,  22,  71],
       [230, 104,   0,   0],
       [231, 197, 132, 105],
       [232,  58,  32,  10],
       [233, 108, 170, 125],
       [234,  37,   5,   5],
       [235,  46,  44, 121],
       [236,  26,  61,  62],
       [237,   6,  96,  52],
       [238, 110, 111,  65],
       [239, 220, 150,   3],
       [240,  46,  43,  34],
       [241, 168,  60,  75],
       [242,   0, 187, 189],
       [243, 113,   0, 191],
       [244, 119, 117, 171],
       [245,   0,  94,  44],
       [246,  57,  67,  69],
       [247, 179, 141,  67],
       [248, 133,  16,  45],
       [249, 203,  33,  40],
       [250, 197,  87,  28],
       [251, 182,  35, 117],
       [252, 215, 194, 146],
       [253, 150,  60,  55],
       [254,  80,  48,  48],
       [255, 158,  66, 173],
       [256,   0,  57,  56],
       [257, 117,  67, 167],
       [258, 168,   0, 183],
       [259, 220, 184, 145],
       [260, 220,   5, 130],
       [261,  97,  45,  74],
       [262, 220, 135,  35],
       [263,   0, 172, 229],
       [264,  70,  48,  60],
       [265,   5,  79, 168],
       [266, 158, 136,  89],
       [267, 201, 182, 156],
       [268,  73,  87,  87],
       [269,  12, 126, 229],
       [270, 179,   8,  86],
       [271,  98, 169,  83],
       [272, 114,  95,   8],
       [273,   0,   0, 137],
       [274, 189, 151,  78],
       [275,  57,  75,  64],
       [276, 159, 160, 111],
       [277,  66,  46,  65],
       [278, 205, 214, 194],
       [279,   2,  37, 147],
       [280,  91, 227, 229],
       [281, 220,   0,  46],
       [282,   0, 233, 229],
       [283,   0, 233,   0],
       [284,  79,   0, 229],
       [285, 209, 169, 229],
       [286, 168, 233,   0],
       [287, 156,   0, 229],
       [288,  40,   0, 229],
       [289, 108,   0, 229],
       [290, 220, 233,   0],
       [291,  53, 181, 103],
       [292, 145, 113, 132],
       [293, 114, 181, 143],
       [294, 158, 136,  89],
       [295,  94,   8,   9],
       [296, 146,  36, 119],
       [297, 209,   0, 142],
       [298, 193, 152,  95],
       [299,  50,  75,  67],
       [300,  51, 103,  49],
       [301, 220,  24,   0],
       [302,  76,  66,  14],
       [303, 170,  16,  25],
       [304, 143,  18,  19],
       [305, 190,  70,  19],
       [306, 217, 124, 153],
       [307, 212, 213, 124],
       [308, 202, 200, 113],
       [309, 220, 228, 220],
       [310, 220, 172,   0],
       [311, 220,   5, 130],
       [312, 168, 233,   0],
       [313, 220,   0,  62],
       [314,   1,  50,  18],
       [315,  17, 121,  19],
       [316, 130, 105,  74],
       [317,   0,  96, 167],
       [318,  99,  79, 124],
       [319, 168, 233,   0],
       [320, 163,  28,  55],
       [321, 211,  56, 120],
       [322, 220,   0, 229],
       [323, 158,  66, 173],
       [324, 220, 101, 229],
       [325, 163,  49, 100],
       [326, 192, 114,   0],
       [327, 168,  84,  84],
       [328, 184, 200, 200],
       [329, 192, 137, 219],
       [330, 213, 226, 229],
       [331, 141,  83,   0],
       [332,  65, 112, 164],
       [333, 194, 212, 225],
       [334, 177, 157,  39],
       [335, 220, 195,   0],
       [336, 117,  83,   6],
       [337, 217, 176,   0],
       [338, 220, 203,   0],
       [339, 182, 147,  17],
       [340, 132, 208, 141],
       [341,  94, 110, 111],
       [342,  45,  71,  52],
       [343,  94, 110, 111],
       [344, 155, 171, 169],
       [345,   0, 233,   0],
       [346,  10, 154, 103],
       [347,   0, 110,   0],
       [348,   0, 150, 102],
       [349,   0, 140,  89],
       [350,   0, 147,  64],
       [351,  70, 159,  34],
       [352, 137, 233,  30],
       [353, 133, 136, 116],
       [354,   0, 233, 109],
       [355,  70,  40,  68],
       [356,  44,  90, 186],
       [357,  55,   8, 225],
       [358, 197, 194,  89],
       [359,  40, 233,   0],
       [360, 165,   0,   7],
       [361, 182, 127,   0],
       [362,  94, 110,   0],
       [363, 187,  97, 229],
       [364, 209,   0, 142],
       [365, 205, 233, 220],
       [366,   0, 108, 170],
       [367,  47, 103,  89],
       [368, 220,  12, 185],
       [369, 220,  87, 162],
       [370,  33,  76,  43],
       [371,  81, 148, 190],
       [372, 217, 225,  77],
       [373,   0,  19, 132],
       [374, 143, 216,  76],
       [375,   4, 118, 110],
       [376, 169,  74,  75],
       [377, 191, 150,  71],
       [378,  79,   0, 229],
       [379,   0,  47,  88],
       [380,  48,   0, 113],
       [381,   0,  31, 148],
       [382, 220,  61,   0],
       [383, 151,   7, 171],
       [384, 157,  39,  28],
       [385,  60,  61, 186],
       [386, 209, 220, 215],
       [387,   0, 126,   0],
       [388, 220, 233, 220],
       [389,   0, 150,  89],
       [390, 213, 202, 108],
       [391, 179,  42,  45],
       [392, 129, 158,  77],
       [393,  32,  37,  36],
       [394, 215, 198,  77],
       [395, 154, 198,  71],
       [396,  22, 153, 117],
       [397,  49, 169,   8],
       [398,  90,  11,  63],
       [399, 160, 159, 128],
       [400, 205, 210, 122],
       [401, 196,   0, 187],
       [402,  93, 102,  32],
       [403, 178, 183, 201],
       [404,  20,  80, 137],
       [405, 219, 232,  19],
       [406, 133, 168, 138],
       [407, 171,   2,  17],
       [408, 168, 185, 229],
       [409, 220, 220, 223],
       [410, 146, 107, 200],
       [411, 161, 177, 188],
       [412, 113,  69, 214],
       [413, 202, 112, 217],
       [414, 194, 210, 225],
       [415, 216, 156, 190],
       [416, 114, 105, 164],
       [417, 216, 142, 207],
       [418, 194, 210, 225],
       [419,  90, 230,   0],
       [420, 220, 225,   0],
       [421, 220, 228, 184],
       [422, 191, 233,   0],
       [423,   9,   3,   1],
       [424, 218, 193, 159],
       [425, 137, 196, 210],
       [426, 146,  83,  13],
       [427, 194,  85,  96],
       [428, 205, 110, 111],
       [429, 112, 185, 213],
       [430, 210,  87, 128],
       [431, 188, 233, 229],
       [432, 214, 114, 218],
       [433, 215, 228, 190],
       [434, 176, 191, 191],
       [435, 109, 217, 127],
       [436, 205, 210, 122],
       [437, 142, 138, 197],
       [438, 220, 164, 173],
       [439, 197,  98,  65],
       [440, 220, 142, 105],
       [441, 220, 135, 135],
       [442,  15, 160, 151],
       [443, 100, 187, 225],
       [444,  86, 118, 135],
       [445, 144, 121,  91],
       [446, 194, 125, 153],
       [447, 220, 233, 204],
       [448, 164, 144, 179],
       [449, 156, 233,   0],
       [450,  30, 186,  34],
       [451,   0, 233,   0],
       [452, 121, 176, 126],
       [453,   8,  71,  63],
       [454, 215, 220, 210],
       [455, 158, 136,  89],
       [456,  76, 142, 200],
       [457,  56,  57,  62],
       [458, 194,  16,  17],
       [459, 220,   0, 229],
       [460, 166,  14, 106],
       [461, 220,   0, 127],
       [462, 134, 220, 189],
       [463, 213, 222, 229],
       [464, 157,  46,   0],
       [465, 216, 216,  76],
       [466,  65,  62, 200],
       [467, 140, 198,  65],
       [468, 115, 136, 151],
       [469, 220, 112,  50],
       [470,  84, 177,  83],
       [471, 101,   0, 115],
       [472, 160,  17,  55],
       [473,  94,   0,   0],
       [474, 141,  33,  79],
       [475, 188, 159, 229],
       [476, 110,  77,  91],
       [477, 203, 134, 151],
       [478,  83, 176, 226],
       [479, 193, 165,  43],
       [480,  70, 201, 151],
       [481,   0,   0, 184],
       [482, 190,  78,  28],
       [483, 139,  46,  37],
       [484, 208, 209, 152],
       [485,  27,  62, 133],
       [486,  10,  38,  29],
       [487, 185, 142, 201],
       [488, 151,  67, 191],
       [489,   0,  85, 146],
       [490, 112,  94, 199],
       [491, 152,  36, 115],
       [492, 134,  46,  87],
       [493,  37, 161,  96],
       [494,  89,  86, 217],
       [495, 165, 200, 117],
       [496,   0, 228, 136],
       [497,  71,  58,  54],
       [498,  46, 190, 183],
       [499,  88,  50,  43],
       [500, 181,  79,  43],
       [501, 163,   6, 115],
       [502, 213, 166, 103],
       [503, 213, 202, 108],
       [504, 218, 170, 162],
       [505,   8,   9,  95],
       [506,   0,  55,  67],
       [507, 220, 178, 171],
       [508,  39, 162, 119],
       [509, 210, 233, 225],
       [510, 116, 233, 134],
       [511, 220, 208, 205],
       [512, 215, 215, 195],
       [513, 114,  95,   8],
       [514,  83, 151, 174],
       [515, 138, 173,   0],
       [516, 137, 203, 154],
       [517,  28, 168, 125],
       [518, 117, 104, 123],
       [519,   7,  51,  43],
       [520, 162,  57, 122],
       [521, 220, 199,  72],
       [522,  16,  48,  14],
       [523, 211, 155, 178],
       [524,  23, 110,   0],
       [525, 215, 198,  77],
       [526, 220, 202, 154],
       [527,   0,   0, 111],
       [528, 220, 145,  50],
       [529, 219,  47,  82],
       [530,  35, 233,   5],
       [531, 179, 113, 109],
       [532, 128, 201, 216],
       [533,  52, 126,  35],
       [534,   0, 101, 169],
       [535, 168, 101,  19],
       [536,   0, 110,   0],
       [537, 171, 163,  43],
       [538, 218, 223, 210],
       [539,  88,  86, 103],
       [540,  71,  34,  54],
       [541, 157, 110, 112],
       [542,  94, 110,   0],
       [543,  37,  37,  15],
       [544,  75, 124,  20],
       [545, 118, 167,  98],
       [546,  33,  40,  41],
       [547, 148, 114, 148],
       [548, 220, 108,   0],
       [549, 220, 140,   0],
       [550, 220,  51,   0],
       [551, 216, 135,  16],
       [552, 220, 147,   0],
       [553, 182,  94, 194],
       [554,  69,  49,  18],
       [555, 117,   0,   0],
       [556,  42,  56,  59],
       [557, 220,  92,  57],
       [558,   0,  17,  54],
       [559,   0,  84,   0],
       [560,  21,  42, 206],
       [561,  72,  24,  79],
       [562, 153, 192, 210],
       [563, 139, 217, 217],
       [564, 116, 100,  68],
       [565, 139,  46,  37],
       [566, 119, 178, 206],
       [567, 185, 155, 156],
       [568, 182, 120,  85],
       [569, 135, 186, 218],
       [570, 194, 171, 120],
       [571, 202, 212, 151],
       [572, 116, 229, 134],
       [573, 184, 189, 229],
       [574, 214, 114, 209],
       [575, 215, 198, 201],
       [576, 185, 142, 201],
       [577, 183,  94, 130],
       [578, 114, 202, 189],
       [579, 165, 174, 167],
       [580, 200, 215, 168],
       [581, 153, 134, 108],
       [582, 183,  94, 130],
       [583,  87,   8,  57],
       [584, 220, 218, 193],
       [585,  53, 181, 103],
       [586, 138, 180, 186],
       [587,  96,  87,  67],
       [588, 171, 188, 176],
       [589,  86, 201, 102],
       [590, 209, 136, 174],
       [591, 220, 161,  54],
       [592, 186, 147, 145],
       [593, 144, 139, 163],
       [594, 220,  87,  80],
       [595, 167, 135, 180],
       [596, 218, 231, 133],
       [597,  94,   0, 111],
       [598,  56,  86, 103],
       [599, 220, 209, 162],
       [600, 220, 184, 145],
       [601, 220, 185, 135],
       [602, 220, 198, 165],
       [603, 215, 203, 154],
       [604, 174, 207,  33],
       [605, 198, 205, 179],
       [606, 101, 196, 172],
       [607, 148,  86, 143],
       [608, 194, 207,   0],
       [609, 168, 185, 229],
       [610,  10,  41, 167],
       [611,   0, 148, 130],
       [612,  30,   4, 105],
       [613, 181, 126,  72],
       [614, 212, 108, 169],
       [615,  80,  11,  12],
       [616, 168,  36,  35],
       [617, 219,  24, 143],
       [618, 200,  70,   0],
       [619, 169, 115,  46],
       [620, 187,   0, 229],
       [621,   0, 219, 119],
       [622,   3,  38,  21],
       [623, 218, 201, 210],
       [624,   1, 103,  93],
       [625, 220, 174, 182],
       [626, 220, 201, 222],
       [627, 220, 135,  84],
       [628, 195, 154, 186],
       [629, 212, 125, 148],
       [630, 112, 179,  97],
       [631, 193, 208, 206],
       [632, 107,  51, 115],
       [633, 185, 142, 201],
       [634, 220,  72,  38],
       [635, 141, 205, 210],
       [636, 220, 125,   0],
       [637,  80,  11,  12],
       [638,   0,  34,  67],
       [639, 187,   0, 229],
       [640, 168, 118, 135],
       [641, 220,  99,   9],
       [642,  73,  38, 137],
       [643,  94,   0, 111],
       [644, 114, 102, 164],
       [645, 122,   0, 177],
       [646, 219,  60, 198],
       [647,  53,  46,  60],
       [648, 124,  16, 220],
       [649,  54,  54,  62],
       [650,  62, 120, 149],
       [651, 220,  38,  77],
       [652, 216, 153,  79],
       [653, 191, 158,  76],
       [654, 110,  77,  91],
       [655, 190,  62, 134],
       [656, 144,  50,  90],
       [657,  95,  84,  51],
       [658, 220,  36, 183],
       [659, 191,  21,  89],
       [660, 220,   0,   0],
       [661, 129,  26,  26],
       [662,  99,   1,   2],
       [663, 207,   0,  44],
       [664, 161,  15,  35],
       [665, 220,  65,  56],
       [666, 201,  11,  21],
       [667, 219,  23,   3],
       [668, 163,   6, 115],
       [669, 135,  60,  66],
       [670,  55,  29, 111],
       [671,   0,  19, 117],
       [672,   0,  46,  47],
       [673, 206, 149, 228],
       [674, 179,   0,  47],
       [675,  93, 128, 188],
       [676, 131,  89, 186],
       [677, 147,  84, 190],
       [678, 141,  33,  79],
       [679,  42,  54,  35],
       [680,   0, 185, 183],
       [681, 220,   0, 109],
       [682, 214,  48, 139],
       [683,  71,  54,  53],
       [684, 148,  92, 104],
       [685, 191,  22,  38],
       [686, 220,  84, 183],
       [687, 134, 134, 150],
       [688, 109,  75,  76],

In [345]:
y

array(['62120149', '033125', '82142173', '1272240', '205226229',
       '1912238', '161811', '203202184', '1932764', '2201720', '2201070',
       '2203245', '11784183', '12818041', '207221222', '169131100',
       '11074114', '971029', '215215195', '01100', '1061640', '216187159',
       '0233229', '92233192', '486517', '365058', '19719489', '143171163',
       '10015189', '22013584', '1292626', '2182170', '78108111',
       '5811231', '0108229', '205233229', '102188220', '125183221',
       '209176174', '16153184', '215211163', '22020637', '9014116',
       '97114113', '116101106', '153192210', '12211195', '210223200',
       '1202149', '220208176', '382715', '2199377', '1566165', '000',
       '3817316', '193825', '364338', '220215184', '1299582', '29122211',
       '136209217', '215220169', '00229', '126144188', '1399228',
       '70135183', '172134166', '0129156', '0117168', '3136135',
       '1453228', '380111', '10327206', '18675114', '885043', '0131164',
       '191198180', '16800', '08861', '1003579', '094229', '14614849',
       '1674768', '11154194', '702330', '156130208', '1601755', '2200109',
       '93212202', '174140212', '209169229', '22067144', '21679109',
       '04822', '16910834', '114570', '1292626', '220175183', '195232229',
       '205200113', '467894', '94017', '186166117', '168670', '1979865',
       '1033621', '15436145', '802581', '568697', '63139141', '110145158',
       '08944', '20111729', '191019', '2202240', '13010574', '483918',
       '125927', '127175154', '15813689', '203169183', '8711689',
       '2202180', '2201090', '19295105', '0172229', '592317', '1611342',
       '0185135', '11409', '179047', '1995849', '220040', '220148180',
       '1441011', '117168201', '20112718', '6426103', '111143186',
       '136206156', '0105148', '26114107', '143233229', '47133188',
       '1863481', '20042114', '0105148', '2364169', '77137175', '0104146',
       '1884333', '12410273', '215194146', '345162', '194125153',
       '1872330', '922330', '1863481', '220165177', '1697475', '18693142',
       '1326392', '1344014', '89450', '1758714', '2201490', '116111106',
       '1914836', '1758714', '192189140', '216185211', '053152',
       '1758714', '796039', '119201229', '213113104', '03081',
       '105128153', '1499735', '18212085', '1379387', '1679165',
       '1178484', '220400', '22010864', '213113104', '2204647', '1024552',
       '21621676', '1441011', '68131216', '220226200', '220226211',
       '220170197', '220231188', '184544', '155034', '0233229', '0165214',
       '22023333', '20520632', '00121', '694918', '624168', '12800',
       '9351108', '1168779', '1697352', '0121121', '5686103', '149116157',
       '133151150', '13517', '04788', '92018', '15416589', '464334',
       '8361133', '1040121', '03684', '578930', '2201220', '11735183',
       '86139182', '2717444', '11493194', '1594219', '19566111', '036135',
       '1002271', '10400', '197132105', '583210', '108170125', '3755',
       '4644121', '266162', '69652', '11011165', '2201503', '464334',
       '1686075', '0187189', '1130191', '119117171', '09444', '576769',
       '17914167', '1331645', '2033340', '1978728', '18235117',
       '215194146', '1506055', '804848', '15866173', '05756', '11767167',
       '1680183', '220184145', '2205130', '974574', '22013535', '0172229',
       '704860', '579168', '15813689', '201182156', '738787', '12126229',
       '179886', '9816983', '114958', '00137', '18915178', '577564',
       '159160111', '664665', '205214194', '237147', '91227229', '220046',
       '0233229', '02330', '790229', '209169229', '1682330', '1560229',
       '400229', '1080229', '2202330', '53181103', '145113132',
       '114181143', '15813689', '9489', '14636119', '2090142', '19315295',
       '507567', '5110349', '220240', '766614', '1701625', '1431819',
       '1907019', '217124153', '212213124', '202200113', '220228220',
       '2201720', '2205130', '1682330', '220062', '15018', '1712119',
       '13010574', '096167', '9979124', '1682330', '1632855', '21156120',
       '2200229', '15866173', '220101229', '16349100', '1921140',
       '1688484', '184200200', '192137219', '213226229', '141830',
       '65112164', '194212225', '17715739', '2201950', '117836',
       '2171760', '2202030', '18214717', '132208141', '94110111',
       '457152', '94110111', '155171169', '02330', '10154103', '01100',
       '0150102', '014089', '014764', '7015934', '13723330', '133136116',
       '0233109', '704068', '4490186', '558225', '19719489', '402330',
       '16507', '1821270', '941100', '18797229', '2090142', '205233220',
       '0108170', '4710389', '22012185', '22087162', '337643', '81148190',
       '21722577', '019132', '14321676', '4118110', '1697475', '19115071',
       '790229', '04788', '480113', '031148', '220610', '1517171',
       '1573928', '6061186', '209220215', '01260', '220233220', '015089',
       '213202108', '1794245', '12915877', '323736', '21519877',
       '15419871', '22153117', '491698', '901163', '160159128',
       '205210122', '1960187', '9310232', '178183201', '2080137',
       '21923219', '133168138', '171217', '168185229', '220220223',
       '146107200', '161177188', '11369214', '202112217', '194210225',
       '216156190', '114105164', '216142207', '194210225', '902300',
       '2202250', '220228184', '1912330', '931', '218193159', '137196210',
       '1468313', '1948596', '205110111', '112185213', '21087128',
       '188233229', '214114218', '215228190', '176191191', '109217127',
       '205210122', '142138197', '220164173', '1979865', '220142105',
       '220135135', '15160151', '100187225', '86118135', '14412191',
       '194125153', '220233204', '164144179', '1562330', '3018634',
       '02330', '121176126', '87163', '215220210', '15813689', '76142200',
       '565762', '1941617', '2200229', '16614106', '2200127', '134220189',
       '213222229', '157460', '21621676', '6562200', '14019865',
       '115136151', '22011250', '8417783', '1010115', '1601755', '9400',
       '1413379', '188159229', '1107791', '203134151', '83176226',
       '19316543', '70201151', '00184', '1907828', '1394637', '208209152',
       '2762133', '103829', '185142201', '15167191', '085146', '11294199',
       '15236115', '1344687', '3716196', '8986217', '165200117',
       '0228136', '715854', '46190183', '885043', '1817943', '1636115',
       '213166103', '213202108', '218170162', '8995', '05567',
       '220178171', '39162119', '210233225', '116233134', '220208205',
       '215215195', '114958', '83151174', '1381730', '137203154',
       '28168125', '117104123', '75143', '16257122', '22019972', '164814',
       '211155178', '231100', '21519877', '220202154', '00111',
       '22014550', '2194782', '352335', '179113109', '128201216',
       '5212635', '0101169', '16810119', '01100', '17116343', '218223210',
       '8886103', '713454', '157110112', '941100', '373715', '7512420',
       '11816798', '334041', '148114148', '2201080', '2201400', '220510',
       '21613516', '2201470', '18294194', '694918', '11700', '425659',
       '2209257', '01754', '0840', '2142206', '722479', '153192210',
       '139217217', '11610068', '1394637', '119178206', '185155156',
       '18212085', '135186218', '194171120', '202212151', '116229134',
       '184189229', '214114209', '215198201', '185142201', '18394130',
       '114202189', '165174167', '200215168', '153134108', '18394130',
       '87857', '220218193', '53181103', '138180186', '968767',
       '171188176', '86201102', '209136174', '22016154', '186147145',
       '144139163', '2208780', '167135180', '218231133', '940111',
       '5686103', '220209162', '220184145', '220185135', '220198165',
       '215203154', '17420733', '198205179', '101196172', '14886143',
       '1942070', '168185229', '1041167', '0148130', '304105', '18112672',
       '212108169', '801112', '1683635', '21924143', '200700', '16911546',
       '1870229', '0219119', '33821', '218201210', '110393', '220174182',
       '220201222', '22013584', '195154186', '212125148', '11217997',
       '193208206', '10751115', '185142201', '2207238', '141205210',
       '2201250', '801112', '03467', '1870229', '168118135', '220999',
       '7338137', '940111', '114102164', '1220177', '21960198', '534660',
       '12416220', '545462', '62120149', '2203877', '21615379',
       '19115876', '1107791', '19062134', '1445090', '958451', '22036183',
       '1912189', '22000', '1292626', '9912', '207044', '1611535',
       '2206556', '2011121', '219233', '1636115', '1356066', '5529111',
       '019117', '04647', '206149228', '179047', '93128188', '13189186',
       '14784190', '1413379', '425435', '0185183', '2200109', '21448139',
       '715453', '14892104', '1912238', '22084183', '134134150',
       '1097576', '1356066', '690157', '17700', '153125125', '040149',
       '01984', '4287205', '16628129', '8763150', '21519877', '174070',
       '188378', '119314', '220024', '1528324', '189124133', '1321194',
       '945211', '14847203', '1822850', '06846', '104514', '220850',
       '20917832', '22012287', '220127145', '159160111', '114958',
       '20019347', '20914679', '114958', '1110140', '5310626', '20464166',
       '085146', '16714337', '220200', '21820437', '2201960', '85233105',
       '087131', '2512171', '3055', '220223217', '2201680', '80485',
       '10310376', '013979', '217219172', '22093229', '101298',
       '157174172', '16747157', '09899', '100187214', '17195156',
       '7472184', '80110127', '036135', '1124448', '2173110', '220228225',
       '204174227', '1312300', '0233109', '1825105', '45112162',
       '21519877', '11700', '518488', '19219793', '22018535', '215194146',
       '175162122', '214590', '2071150', '2201850', '19295105', '464334',
       '104115119', '173220172', '213113104', '209176174', '0110111',
       '3499118', '0112109', '17137101', '169690', '1909674', '180172196',
       '18693142', '217119153', '123168163', '18812344', '183195190',
       '2022100', '2208254', '8490172', '220181107', '21820437',
       '94110111', '09977', '097186', '42106173', '186152118', '14696112',
       '28193179', '0233218', '124194162', '905455', '1035589', '701544',
       '036151', '181059', '101102175', '5686132', '2201610', '3718995',
       '22093229', '3141125', '4284223', '676354', '220201181',
       '61128209', '14811723', '22023384', '15018', '8934', '1381625',
       '18915518', '061134', '11700', '2201850', '176046', '208209152',
       '16216172', '1641096', '43161155', '1914836', '1817943',
       '12416220', '1080229', '3056160', '920229', '991156', '202112217',
       '4111291', '1112321', '1221237', '18212112', '220142119',
       '1220229', '04849', '128222224', '686666', '210202161',
       '220233229', '210223223', '126155188', '22049145', '21790115',
       '823139', '713454', '165142200', '15813689', '83116103',
       '20459129', '2202330', '11818634', '2031850', '2201910',
       '22015649', '2202180', '21923235', '05149', '247110'], dtype=object)

In [347]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# # Split data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# abc = AdaBoostClassifier(n_estimators=100, random_state=42)

# # Fit the classifier to the training data
# abc.fit(X_train, y_train)

# # Predict color names for the test data
# y_pred = abc.predict(X_test)

# # Calculate the accuracy score of the model
# accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy:", accuracy)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=60)

# Create a random forest classifier with 100 trees
rfc = RandomForestClassifier(n_estimators=100, random_state=60)

# Fit the classifier to the training data
rfc.fit(X_train, y_train)

# Predict color names for the test data
y_pred = rfc.predict(X_test)

# Calculate the accuracy score of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.15606936416184972